version: "3.7"

services:
    # image project
    app:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on: 
            - redis
        networks: 
            - laravel
    
    # nginx
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports: 
            - "8989:80"
        volumes: 
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks: 
            - laravel
    postgres:
        image: postgres
        restart: unless-stopped
        ports:
            - "5432:5432"
        volumes:
            - ./.docker/postgres/dbdata:/var/lib/postgres
        environment:
            - POSTGRES_PASSWORD=root
        networks:
            - laravel
    

    # db mysql
    # mysql:
    #     image: mysql
    #     restart: unless-stopped
    #     environment: 
    #         MYSQL_DATABASE: appdatabase
    #         MYSQL_ROOT_PASSWORD: root
    #         MYSQL_PASSWORD: root
    #         MYSQL_USER: root
    #     volumes: 
    #         - ./.docker/mysql/dbdata:/var/lib/mysql
    #     ports: 
    #         - "3388:3306"
    #     networks: 
    #         - laravel
    # phpmyadmin:
    #     image: phpmyadmin/phpmyadmin
    #     container_name: phpmyadmin
    #     restart: unless-stopped
    #     ports:
    #         - "3400:80"
    #     depends_on:
    #         - mysql
    #     networks:
    #         - laravel

    # queue
    queue:
        image: especializati/laravel-app
        restart: unless-stopped
        command: "php artisan queue:work"
        volumes: 
            - ./:/var/www
        depends_on: 
            - redis
            - app
        networks: 
            - laravel

    # redis
    redis:
        image: redis:latest
        networks: 
            - laravel

networks: 
    laravel:
        driver: bridge